#!/bin/bash -l

## THE SCRIPT RUNS (SECOND TIME) A BATTERY OF TEST CALCULATIONS TO TEST THE PGO COMPILATION ##

PROGDIR="/home/mgimferrer/APOST3D"
TESTDIR="${PROGDIR}/compiler-testset"
APOST="${PROGDIR}/apost3d"

cd ${TESTDIR}

echo " "
echo " RUNNING TEST CALCULATIONS FOR PGO COMPILATION (STEP 2) "
for mol in C2H6-B3LYP FeCO2-PBEPBE CH3F FeO4-2; do
  STAT=" PERFORMING CALCULATION FOR ${mol} "
  echo "${STAT}"
  /usr/bin/time -f " %E real,%U user,%S sys, %P CPU Percentage, %M Max Resident Set Size (Kb)" ${APOST} ${mol} > ${mol}.apost2
done
echo " "
echo " STEP 2 DONE "
echo " "

